### ISSUE TITLE
ValueError: need more than 2 values to unpack?

### ISSUE THREAD

**Issue by luoolu** [blankblankblank123/MCANet_CVPR2020#1]
Traceback (most recent call last):
  File "/home/xkjs/PycharmProjects/MCANet_CVPR2020/demo.py", line 122, in <module>
    pd_vis = vis(im, pd, 0.7)
  File "/home/xkjs/PycharmProjects/MCANet_CVPR2020/libs/utils/vis.py", line 18, in vis
    _, contours, hierarch, temp = cv2.findContours(binary_out.astype(np.uint8), cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)
ValueError: need more than 2 values to unpack

**Comment by blankblankblank123** [comment]
Bug fixed.
